#!/usr/bin/env bash

# Central public hostname policy for the Torhole reverse proxy.
# Values are labels under REVERSE_PROXY_DOMAIN, not full FQDNs.

TORHOLE_HOST_TORHOLE="${TORHOLE_HOST_TORHOLE:-torhole}"
TORHOLE_HOST_AUTH="${TORHOLE_HOST_AUTH:-auth}"
TORHOLE_HOST_GRAFANA="${TORHOLE_HOST_GRAFANA:-grafana}"
TORHOLE_HOST_PROMETHEUS="${TORHOLE_HOST_PROMETHEUS:-prometheus}"
TORHOLE_HOST_ALERTMANAGER="${TORHOLE_HOST_ALERTMANAGER:-alertmanager}"
TORHOLE_HOST_DOCKHAND="${TORHOLE_HOST_DOCKHAND:-dockhand}"
TORHOLE_HOST_PIHOLE_TRUSTED="${TORHOLE_HOST_PIHOLE_TRUSTED:-pihole-trusted}"
TORHOLE_HOST_PIHOLE_IOT="${TORHOLE_HOST_PIHOLE_IOT:-pihole-iot}"

TORHOLE_ALIAS_TORHOLE="${TORHOLE_ALIAS_TORHOLE:-th}"
TORHOLE_ALIAS_GRAFANA="${TORHOLE_ALIAS_GRAFANA:-gf}"
TORHOLE_ALIAS_PROMETHEUS="${TORHOLE_ALIAS_PROMETHEUS:-prom}"
TORHOLE_ALIAS_ALERTMANAGER="${TORHOLE_ALIAS_ALERTMANAGER:-am}"
TORHOLE_ALIAS_DOCKHAND="${TORHOLE_ALIAS_DOCKHAND:-dh}"
TORHOLE_ALIAS_PIHOLE_TRUSTED="${TORHOLE_ALIAS_PIHOLE_TRUSTED:-pt}"
TORHOLE_ALIAS_PIHOLE_IOT="${TORHOLE_ALIAS_PIHOLE_IOT:-pi}"

torhole_public_hosts_csv() {
  local hosts=(
    "$TORHOLE_HOST_TORHOLE" \
    "$TORHOLE_HOST_AUTH" \
    "$TORHOLE_HOST_GRAFANA" \
    "$TORHOLE_HOST_PROMETHEUS" \
    "$TORHOLE_HOST_ALERTMANAGER" \
    "$TORHOLE_HOST_DOCKHAND" \
    "$TORHOLE_HOST_PIHOLE_TRUSTED" \
    "$TORHOLE_ALIAS_TORHOLE" \
    "$TORHOLE_ALIAS_GRAFANA" \
    "$TORHOLE_ALIAS_PROMETHEUS" \
    "$TORHOLE_ALIAS_ALERTMANAGER" \
    "$TORHOLE_ALIAS_DOCKHAND" \
    "$TORHOLE_ALIAS_PIHOLE_TRUSTED"
  )
  if [[ "${TORHOLE_TOPOLOGY:-vlan}" == "vlan" ]]; then
    hosts+=("$TORHOLE_HOST_PIHOLE_IOT" "$TORHOLE_ALIAS_PIHOLE_IOT")
  fi
  printf '%s\n' "${hosts[@]}" | awk 'NF' | paste -sd, -
}

torhole_protected_hosts_regex() {
  local hosts=(
    "$TORHOLE_HOST_TORHOLE" \
    "$TORHOLE_HOST_GRAFANA" \
    "$TORHOLE_HOST_PROMETHEUS" \
    "$TORHOLE_HOST_ALERTMANAGER" \
    "$TORHOLE_HOST_DOCKHAND" \
    "$TORHOLE_HOST_PIHOLE_TRUSTED" \
    "$TORHOLE_ALIAS_TORHOLE" \
    "$TORHOLE_ALIAS_GRAFANA" \
    "$TORHOLE_ALIAS_PROMETHEUS" \
    "$TORHOLE_ALIAS_ALERTMANAGER" \
    "$TORHOLE_ALIAS_DOCKHAND" \
    "$TORHOLE_ALIAS_PIHOLE_TRUSTED"
  )
  if [[ "${TORHOLE_TOPOLOGY:-vlan}" == "vlan" ]]; then
    hosts+=("$TORHOLE_HOST_PIHOLE_IOT" "$TORHOLE_ALIAS_PIHOLE_IOT")
  fi
  printf '%s\n' "${hosts[@]}" \
    | awk 'NF && !seen[$0]++ { gsub(/[][\\.^$*+?(){}|]/, "\\\\&"); print }' \
    | paste -sd'|' -
}
