#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT="${ROOT_DIR}/monitoring/caddy/topology-sites.caddy"
ENV_FILE="${ROOT_DIR}/.env"

TORHOLE_TOPOLOGY="${TORHOLE_TOPOLOGY:-}"
if [[ -z "$TORHOLE_TOPOLOGY" && -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1091
  source "$ROOT_DIR/ops/lib/load-env.sh"
  load_env_file "$ENV_FILE"
fi
TORHOLE_TOPOLOGY="${TORHOLE_TOPOLOGY:-vlan}"

case "$TORHOLE_TOPOLOGY" in
  single-lan)
    cat >"$OUTPUT" <<'EOF'
# Generated by 14-render-caddy-topology.sh.
# Single-LAN has no second Pi-hole site.
EOF
    ;;
  vlan)
    cat >"$OUTPUT" <<'EOF'
# Generated by 14-render-caddy-topology.sh.
{$TORHOLE_WEB_SCHEME}://{$TORHOLE_HOST_PIHOLE_IOT}.{$REVERSE_PROXY_DOMAIN}, {$TORHOLE_WEB_SCHEME}://{$TORHOLE_ALIAS_PIHOLE_IOT}.{$REVERSE_PROXY_DOMAIN} {
  import tls_mode
  route {
    import access_gate
    @root path /
    redir @root /admin/ 302
    reverse_proxy pihole_iot:80
  }
}
EOF
    ;;
  *)
    echo "TORHOLE_TOPOLOGY must be single-lan or vlan." >&2
    exit 1
    ;;
esac

chmod 600 "$OUTPUT"
echo "OK: Caddy sites rendered for Advanced ${TORHOLE_TOPOLOGY}."
