#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing .env at: $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1091
source "$ROOT_DIR/ops/lib/load-env.sh"
load_env_file "$ENV_FILE"
# shellcheck disable=SC1091
source "${ROOT_DIR}/ops/lib/torhole-hostnames.sh"

HOST_MGMT_IP="${HOST_MGMT_IP:-}"
# Where the public hostnames should resolve. Defaults to this host (Caddy),
# but can point at an external front (e.g. NPM on staging) so re-renders
# don't clobber a proxy-fronted setup.
REVERSE_PROXY_TARGET_IP="${REVERSE_PROXY_TARGET_IP:-$HOST_MGMT_IP}"
REVERSE_PROXY_DOMAIN="${REVERSE_PROXY_DOMAIN:-}"
TORHOLE_PUBLIC_DNS_HOSTS="$(torhole_public_hosts_csv)"
TORHOLE_DNS_HOSTS="${TORHOLE_DNS_HOSTS:-}"
PIHOLE_LOCAL_DNS_RECORDS="${PIHOLE_LOCAL_DNS_RECORDS:-}"

if [[ -z "$REVERSE_PROXY_TARGET_IP" || -z "$REVERSE_PROXY_DOMAIN" ]]; then
  echo "Skipping reverse proxy DNS render: HOST_MGMT_IP/REVERSE_PROXY_TARGET_IP or REVERSE_PROXY_DOMAIN not set."
  exit 0
fi

IFS=',' read -r -a TORHOLE_DNS_HOST_ARRAY <<<"${TORHOLE_PUBLIC_DNS_HOSTS},${TORHOLE_DNS_HOSTS}"
DNS_LINES=()
SEEN_TORHOLE_HOSTS="|"

is_valid_ipv4() {
  local ip="$1"

  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1

  IFS='.' read -r -a octets <<<"$ip"
  for octet in "${octets[@]}"; do
    [[ "$octet" -ge 0 && "$octet" -le 255 ]] || return 1
  done
}

if ! is_valid_ipv4 "$REVERSE_PROXY_TARGET_IP"; then
  echo "Invalid REVERSE_PROXY_TARGET_IP: $REVERSE_PROXY_TARGET_IP" >&2
  exit 1
fi

normalize_dns_host() {
  local host="$1"

  host="$(printf '%s' "$host" | xargs)"
  [[ -n "$host" ]] || return 1

  if [[ "$host" != *.* ]]; then
    host="${host}.${REVERSE_PROXY_DOMAIN}"
  fi

  host="${host,,}"

  if [[ ! "$host" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]]; then
    echo "Invalid DNS host entry: $host" >&2
    exit 1
  fi

  printf '%s\n' "$host"
}

for host in "${TORHOLE_DNS_HOST_ARRAY[@]}"; do
  host="$(printf '%s' "$host" | xargs)"
  [[ -n "$host" ]] || continue

  if [[ ! "$host" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
    echo "Invalid TORHOLE_DNS_HOSTS entry: $host" >&2
    exit 1
  fi

  case "$SEEN_TORHOLE_HOSTS" in
    *"|${host}|"*) continue ;;
  esac
  SEEN_TORHOLE_HOSTS="${SEEN_TORHOLE_HOSTS}${host}|"
  DNS_LINES+=("address=/${host}.${REVERSE_PROXY_DOMAIN}/${REVERSE_PROXY_TARGET_IP}")
done

if [[ -n "$PIHOLE_LOCAL_DNS_RECORDS" ]]; then
  IFS=';' read -r -a CUSTOM_RECORD_ARRAY <<<"$PIHOLE_LOCAL_DNS_RECORDS"

  for record in "${CUSTOM_RECORD_ARRAY[@]}"; do
    record="$(printf '%s' "$record" | xargs)"
    [[ -n "$record" ]] || continue

    if [[ "$record" != *"="* ]]; then
      echo "Invalid PIHOLE_LOCAL_DNS_RECORDS entry: $record" >&2
      exit 1
    fi

    host="${record%%=*}"
    ip="${record#*=}"
    host="$(normalize_dns_host "$host")"
    ip="$(printf '%s' "$ip" | xargs)"

    if ! is_valid_ipv4 "$ip"; then
      echo "Invalid IPv4 address in PIHOLE_LOCAL_DNS_RECORDS: $ip" >&2
      exit 1
    fi

    DNS_LINES+=("address=/${host}/${ip}")
  done
fi

if [[ "${#DNS_LINES[@]}" -eq 0 ]]; then
  echo "Skipping reverse proxy DNS render: TORHOLE_DNS_HOSTS is empty."
  exit 0
fi

for role in trusted iot; do
  out="${ROOT_DIR}/pihole/${role}/etc-dnsmasq.d/98-reverse-proxy-hosts.conf"
  mkdir -p "$(dirname "$out")"
  {
    cat <<EOF
# Generated by ops/scripts/16-render-reverse-proxy-dns.sh
EOF
    printf '%s\n' "${DNS_LINES[@]}"
  } >"$out"
done

echo "OK: reverse proxy DNS entries rendered for ${REVERSE_PROXY_DOMAIN} -> ${REVERSE_PROXY_TARGET_IP}"
