---
- name: Create destination directory
  ansible.builtin.file:
    path: "{{ project_dest }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Sync project files
  ansible.posix.synchronize:
    src: "{{ project_src }}/"
    dest: "{{ project_dest }}/"
    delete: no
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=backups"
      - "--exclude=pihole/*/etc-pihole"
      - "--exclude=pihole/*/etc-dnsmasq.d"

- name: Render .env
  ansible.builtin.template:
    src: env.j2
    dest: "{{ project_dest }}/.env"
    mode: '0640'
    owner: root
    group: root

- name: Render dnscrypt configs
  ansible.builtin.template:
    src: dnscrypt-proxy.toml.j2
    dest: "{{ project_dest }}/dnscrypt/{{ item }}/dnscrypt-proxy.toml"
    mode: '0644'
  loop:
    - trusted
    - iot

- name: Ensure scripts executable
  ansible.builtin.file:
    path: "{{ project_dest }}/ops/scripts"
    mode: '0755'
    recurse: yes

- name: Pull and start stack
  ansible.builtin.command: docker compose --env-file .env -f docker-compose.yml -f docker-compose.monitoring.yml up -d
  args:
    chdir: "{{ project_dest }}"
